# Generated by Django 3.2.6 on 2021-08-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vaccine_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='owner',
            new_name='owners',
        ),
    ]
