# Generated by Django 3.2.6 on 2021-08-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_owner_dog_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Done', 'Done')], default='Todo', max_length=20),
        ),
    ]
