# Generated by Django 3.2.6 on 2021-08-24 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vaccine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='date',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
