# Generated by Django 3.2.6 on 2021-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210824_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='chip_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
